#!/bin/sh
set -e -x

# Installing needed Packages
apk add --update --no-cache --virtual build-dependencies\
  curl=$CURL_VERSION 

apk add --no-cache \
  python3=$PYTHON3_VERSION 

# Installing kubectl
cd /resources
curl -LO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
chmod +x ./kubectl
mv ./kubectl /usr/local/bin/kubectl

# Installing AWS CLI
pip install awscli==${AWSCLI_VERSION}

# Installing aws-iam-authenticator
curl -LO https://amazon-eks.s3-us-west-2.amazonaws.com/${AWS_IAM_AUTHENTICATOR_VERSION}/bin/linux/amd64/aws-iam-authenticator 
chmod +x ./aws-iam-authenticator
mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator

apk del --no-cache build-dependencies 
